### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by SIERRA-880** [Chris00/latex-umons#1]
Can you please add a README.md file with a guide to use the template for exam.
I tried doing examen d'entrainement (26/10/2020) in texmaker using your template but it was too difficult so I'm gonna use my own template.
Thank you

**Comment by Chris00** [comment]
There are two examples `tests-*.tex` which you can follow to use the LaTeX class `tests`.  If they are not clear enough, please be more specific.

(That being said, I invite you to focus your efforts on solving the questions that were asked instead of becoming proficient with LaTeX.  You will have ample time to do that later.)
